lec01.pdf: lec01.tex exp/Normal_Distribution.png exp/MultivariateNormal.png exp/img332_2x.png exp/img333_2x.png exp/img334_2x.png
	pdflatex lec01

exp/Normal_Distribution.png:
	mkdir -p exp
	wget -P exp https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Normal_Distribution_PDF.svg/1920px-Normal_Distribution_PDF.svg.png 
	mv exp/1920px-Normal_Distribution_PDF.svg.png  exp/Normal_Distribution.png

exp/MultivariateNormal.png:
	mkdir -p exp
	wget -P exp https://upload.wikimedia.org/wikipedia/commons/8/8e/MultivariateNormal.png

exp/img332_2x.png:
	mkdir -p exp
	wget -P exp https://ccrma.stanford.edu/~jos/sasp/img332_2x.png

exp/img333_2x.png:
	mkdir -p exp
	wget -P exp https://ccrma.stanford.edu/~jos/sasp/img333_2x.png

exp/img334_2x.png:
	mkdir -p exp
	wget -P exp https://ccrma.stanford.edu/~jos/sasp/img334_2x.png
